halo2_proofs/examples/circuit-layout.rs
halo2_proofs/src/dev.rs
halo2_proofs/src/plonk/circuit.rs
halo2_proofs/src/plonk/lookup.rs
halo2_proofs/tests/lookup_any.rs
halo2_proofs/tests/plonk_api.rs

Currently the lookup error message only contains the lookup index but no lookup name. So debugging lookup error is very difficult. This PR add a name to lookup, so VerifyFailure::Lookup can contain the lookup name.
Solves https://github.com/appliedzkp/halo2/issues/17 and https://github.com/zcash/halo2/issues/441

dev: add name for lookup

---

halo2_proofs/src/arithmetic.rs
halo2_proofs/src/poly/multiopen/shplonk/prover.rs
halo2_proofs/src/poly/multiopen/shplonk/verifier.rs

Before this PR, evaluation of vanishing polynomial was calculated in very suboptimal way ie first calculating the coefficients and then evaluation at a point. Now it's the way it should be that just uses roots and evaluation point.

Vanishing polynomial evaluator

---

halo2_proofs/src/poly/commitment.rs

since we know `s` here, we don't need to do ifft. Directly computing lagranges is much faster.
for k = 16, reduce setup time from 40s to 4s

opt: speed up unsafe_setup

---

halo2_proofs/Cargo.toml

`Cargo.toml` now points to latest `pairing` with a tag.

Tag pairing dependency

---

halo2_proofs/src/plonk/evaluation.rs

Negate the subtrahend when processing `Expression::Sum`

---

halo2_proofs/src/poly/commitment.rs

Used for decision making in downstream projects that want to infer
certain bounds given a `Params{Verifier}` structure.

Params,ParamsVerifier: make k & n public

---

halo2_gadgets/src/ecc/chip/mul_fixed/short.rs
halo2_gadgets/src/sha256/table16.rs
halo2_gadgets/src/utilities.rs
halo2_gadgets/src/utilities/decompose_running_sum.rs
halo2_proofs/examples/shuffle.rs
halo2_proofs/src/circuit.rs
halo2_proofs/src/circuit/floor_planner/single_pass.rs
halo2_proofs/src/circuit/floor_planner/v1.rs
halo2_proofs/src/circuit/floor_planner/v1/strategy.rs
halo2_proofs/src/dev.rs
halo2_proofs/src/dev/cost.rs
halo2_proofs/src/dev/failure.rs
halo2_proofs/src/dev/failure/emitter.rs
halo2_proofs/src/dev/gates.rs
halo2_proofs/src/dev/graph.rs
halo2_proofs/src/dev/graph/layout.rs
halo2_proofs/src/dev/util.rs
halo2_proofs/src/plonk/circuit.rs
halo2_proofs/src/plonk/circuit/compress_selectors.rs
halo2_proofs/src/plonk/evaluation.rs
halo2_proofs/src/plonk/keygen.rs
halo2_proofs/src/plonk/lookup/prover.rs
halo2_proofs/src/plonk/lookup/verifier.rs
halo2_proofs/src/plonk/permutation/prover.rs
halo2_proofs/src/plonk/permutation/verifier.rs
halo2_proofs/src/plonk/prover.rs
halo2_proofs/src/plonk/verifier.rs

Resolves #90.
- Add an enum `Phase`, which has 3 variant `First`, `Second` and `Third` (3 phases should be enough for most cases in my imagination).
- Add a field `phase` to struct `Advice`, variant `Any::Advice` and variant `Expression::Advice`.
- Add a struct `Challenge` and can be allocated by `ConstraintSystem::challenge_usable_after(phase)`, and it's also
1. Used in `VirtualCells::query_challenge(challenge)` to get `Expression::Challenge`.
2. Used in `Layouter::get_challenge(challenge)` to get `Value<F>` (`Value::unknown` if current phase is earlier than requested `challenge`).
- In `create_proof`, `ConcreteCircuit::FloorPlanner::synthesize` will be call as many time as the phases used in the circuit, and `WitnessCollection` will ignore the advice column assignment if phase doesn't …

Implement multi-phase `ConstraintSystem`

---

halo2_proofs/src/plonk/prover.rs
halo2_proofs/src/plonk/verifier.rs
halo2_proofs/src/poly/commitment.rs
halo2_proofs/src/poly/ipa/multiopen/prover.rs
halo2_proofs/src/poly/ipa/multiopen/verifier.rs
halo2_proofs/src/poly/kzg/multiopen/gwc/prover.rs
halo2_proofs/src/poly/kzg/multiopen/gwc/verifier.rs
halo2_proofs/src/poly/kzg/multiopen/shplonk/prover.rs
halo2_proofs/src/poly/kzg/multiopen/shplonk/verifier.rs

This PR aims to make KZG commitment scheme not to query the instance columns from prover, instead calculate the evaluation directly in verifier side.
Current implementation is adding a `const QUERY_INSTANCE: bool` in `Prover` and `Verifier` traits, then in `create_proof` and `verify_proof` it gets the instance evaluation from transcript or by evaluating respectively.

Configurable instance query

---

halo2_gadgets/benches/poseidon.rs

Noticed a small lingering todo in `halo2_gadgets/benches/poseidon.rs` to move the outputs from a `Value` to an instance column. This PR does just that !

chore: instance columns for poseidon bench

---

halo2_proofs/src/dev.rs
halo2_proofs/src/dev/failure.rs
halo2_proofs/src/dev/failure/emitter.rs

Since lookups can only be `Fixed` in Halo2-upstream, we need to add custom suport for the error rendering of dynamic lookups which doesn't come by default when we rebase to upstream.
This means that now we have to print not only `AdviceQuery` results to render the `Expression` that is being looked up. But also support `Instance`, `Advice`, `Challenge` or any other expression types that are avaliable. Therefore, enabling dynamic lookups for `MockProver`.
This addresses the rendering issue, renaming also the `table_columns` variable for `lookup_columns` as the columns do not have the type `TableColumn` by default as opposite to what happens upstream.
`MockProver::assert_satisfied_par` is also included with this PR.
Resolves: #116

Fix MockProver `assert_verify` panic errors

---

halo2_proofs/src/poly/commitment.rs
halo2_proofs/src/poly/kzg/multiopen/shplonk.rs
halo2_proofs/src/poly/kzg/multiopen/shplonk/prover.rs
halo2_proofs/src/poly/query.rs

The main commit d6f562a basically just changes two iterators to `par_iter`. On some circuit I tested this sped up the SHPLONK multi-open proving time at the end of `create_proof` from `12s` to `4s`. 
The other commits are optional and only give minor performance improvements. I used `BTreeSet` for a slightly more efficient/cleaner implementation of getting the distinct rotation sets. Then the last commit (which can be reverted if necessary) adds `Send + Sync` to some traits for further parallelization.

Parallelize SHPLONK multi-open prover

---

halo2_proofs/src/dev/failure.rs

After working on fixing
privacy-scaling-explorations/zkevm-circuits#1024, a bug was found in the verification fn of the MockProver which implies that while finding a FailureLocation, if a Region doesn't contain any rows.
This is fixed by introducing a 2-line solution suggested by @lispc.
Resolves: #117

fix: FailureLocation::find empty-region handling

---

halo2_proofs/Cargo.toml
halo2_proofs/examples/serialization.rs
halo2_proofs/src/helpers.rs
halo2_proofs/src/lib.rs
halo2_proofs/src/plonk.rs
halo2_proofs/src/plonk/permutation.rs
halo2_proofs/src/poly.rs
halo2_proofs/src/poly/kzg/commitment.rs
halo2_proofs/src/poly/kzg/multiopen/gwc/prover.rs
halo2_proofs/src/poly/kzg/multiopen/gwc/verifier.rs
halo2_proofs/src/poly/kzg/multiopen/shplonk/prover.rs
halo2_proofs/src/poly/kzg/multiopen/shplonk/verifier.rs
halo2_proofs/src/poly/kzg/strategy.rs

This resolves the discussion in https://github.com/privacy-scaling-explorations/halo2/pull/103#issuecomment-1338184504
- With feature "serde-raw", field elements are serialized into `[u8; 32]` in Montgomery form `a * R (mod p)` without reduction. Elements are deserialized to `[u64; 4]` and then checked to see that they are less than the modulus `< p`. 
- With feature "raw-unchecked", same as "serde-raw" but the less than modulus check is skipped. Also when possible I favor unwrapping instead of try-branch / try-collect since this feature is optimized for speed.
- With no feature selected it goes back to the previous serialization where Montgomery reduction is done, and curves are stored in affine compressed form.
Should be merged after …

Feature to serialize/deserialize KZG params, verifying key, and proving key into uncompressed Montgomery form

---

halo2_proofs/src/circuit.rs
halo2_proofs/src/circuit/floor_planner/single_pass.rs
halo2_proofs/src/circuit/floor_planner/v1.rs
halo2_proofs/src/circuit/layouter.rs
halo2_proofs/src/dev.rs
halo2_proofs/src/dev/cost.rs
halo2_proofs/src/dev/failure.rs
halo2_proofs/src/dev/failure/emitter.rs
halo2_proofs/src/dev/graph.rs
halo2_proofs/src/dev/graph/layout.rs
halo2_proofs/src/dev/metadata.rs
halo2_proofs/src/plonk/circuit.rs
halo2_proofs/src/plonk/keygen.rs
halo2_proofs/src/plonk/prover.rs

This PR particularly includes:
Resolves: #57 
Here is a list of all of the prints that you can now get with the annotation support: 
**Assert_satisfied - Lookup_any**
<details>
```
error: lookup input does not exist in table
(L0, L1) ∉ ("Inst-Table", "Adv-Table")
Lookup 'lookup' inputs:
L0 = x1 * x0 + (1 - x1) * 0x2
^
| Cell layout in region 'Faulty synthesis':
|   | Offset |Witness example| F0 |
|   +--------+---------------+----+
|   |    1   |       x0      | x1 | <--{ Lookup 'lookup' inputs queried here
|
| Assigned cell values:
|   x0 = 0x5
|   x1 = 1
L1 = x1 * x0 + (1 - x1) * 0x2
^
| Cell layout in region 'Faulty synthesis':
|   | Offset |Witness example| F0 |
|   +--------+---------------+----+
|   |    1   |       x0      | x1 | <--{ Lookup 'lookup' inputs queried here
|
| …
```

Add support for Column annotations for MockProver debugging

---

.github/workflows/ci.yml
.github/workflows/ci_main.yml

This should cut down significantly the CI times on every push done to a branch for a PR.
Resolves: #124

chore: Move Codecov, wasm-build, Bitrot & doc-tests to push

---

halo2_proofs/src/plonk/permutation/keygen.rs

This was missing in #123 so this PR fixes it.

fix: Allow to compare `Assembly` structs

---

halo2_proofs/Cargo.toml
halo2_proofs/src/poly/multiopen_test.rs
halo2_proofs/src/transcript.rs

Keccak256 option added to transcript. 
What is different than blake2b procedure is output size of keccak256 is 32 bytes where it is 64 with blake2. We can of cource find a field element from 32 bytes of keccak256 output but it'd introduce a modulus bias. So in order to make output 64 bytes we followed the approach below.
```
self.state.update(&[KECCAK256_PREFIX_CHALLENGE]);
let mut state_lo = self.state.clone();
let mut state_hi = self.state.clone();
state_lo.update(&[KECCAK256_PREFIX_CHALLENGE_LO]);
state_hi.update(&[KECCAK256_PREFIX_CHALLENGE_HI]);
let hasher_lo = state_lo.clone();
let hasher_hi = state_hi.clone();
let result_lo: [u8; 32] = hasher_lo.finalize().as_slice().try_into().unwrap();
let result_hi: [u8; 32] = hasher_hi.finalize().as_slice().try_into().unwrap();
```
Notice that …

Add keccak256 hasher for transcript

---

halo2_proofs/src/arithmetic.rs
halo2_proofs/src/plonk/permutation/keygen.rs

Reduces proving time on large circuits consistently >=3%.
Builts upon [speed up generate vk pk with multi-thread](https://github.com/privacy-scaling-explorations/halo2/pull/88)
Fixes: https://github.com/privacy-scaling-explorations/halo2/issues/83

 Improve performance of vk & pk keygen and of default `parallelize` chunking size

---

halo2_proofs/src/dev.rs

fix: Support annotations for CellNotAssigned in verify_par

---

halo2_proofs/src/dev.rs

feat: Add `assert_satisfied_at_rows_par` variant

---

halo2_proofs/src/dev.rs
halo2_proofs/src/plonk/circuit.rs

Since the adoption of challenge API in `zkevm-circuits` is not just a small part, it's getting more difficult to use real prover to test the mutli-phase circuit is written properly, so this PR aims to update the `MockProver` to call `synthesize` multiple times to behave exact same as real prover for easier debugging.
It should reduce the chance of issue like https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1086 to happen.
Resolves https://github.com/privacy-scaling-explorations/halo2/issues/102.

Call `synthesize` in `MockProver` multiple times to behave same as real prover

---

halo2_proofs/Cargo.toml
halo2_proofs/benches/commit_zk.rs
halo2_proofs/src/plonk/vanishing/prover.rs
halo2_proofs/src/poly.rs

So I got to a better solution. Which definitely seems solid and secure. And reduces aprox ~5-10x the execution time.
I also ran benches. Here the results:
```
Blinder_poly/serial/18  time:   [28.717 ms 28.779 ms 28.860 ms]                                   
change: [+0.0164% +0.2972% +0.5927%] (p = 0.05 < 0.05)
Blinder_poly/parallel/18                                                                             
time:   [2.4532 ms 2.4792 ms 2.5064 ms]
change: [+0.7593% +2.2239% +3.7108%] (p = 0.00 < 0.05)
Blinder_poly/serial/19  time:   [57.679 ms 57.764 ms 57.866 ms]                                   
change: [-1.1429% -0.7681% -0.4110%] (p = 0.00 < 0.05)
Blinder_poly/parallel/19                                                                             
time:   [5.4919 ms 5.5360 ms …
```

feat: Parallel random blinder poly impl

---

halo2_proofs/src/plonk.rs

Now the value returned when the number of selectors is a multiple of 8 is correct.
Resolves: #175

fix: Fix serialization for VerifyingKey

---

halo2_proofs/src/dev.rs

Revert the check introduced in
https://github.com/privacy-scaling-explorations/halo2/pull/129 to detect double assignments with different values, because it breaks some tests in the zkevm project.
There's a legitimate use case of double assignment with different values, which is overwriting cells in order to perform negative tests (tests with bad witness that should not pass the constraints).
Also in the EVM Circuit from the zkevm project we "abuse" the assignment of cells as a cache: sometimes we assign some cells with a guess value, and later on we reassign with the correct value.
I believe this check is interesting to have, so we could think of ways to add it back as an optional feature.

Revert double-assignment mock prover check

---

halo2_proofs/src/arithmetic.rs

Currently if we take 40 items divided into 12 threads (AMD Ryzen 7800X, Apple M2 Pro or Intel i5-12600) the partitioning will lead to 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7 = 3*11 + 7 = 40. The “remainder” thread will have 2.33x more work to do.
This can be quite extreme for example if we have 351 items to split on 32 cores, 351/32 = 10.96, rounded to 10 with integer division. 10*31 = 310, the last core needs to process 41 items, 4.1x more than the others.
This ensures whatever the number of items and the number of threads, the workload varies by at most 1.
This probably explains why not all cores are used while benchmarking (benchmarks TODO). See also [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law).
Note: I'm not familiar with Rust standard library and parallelism development …

Fix `parallelize` workload imbalance

---

halo2_proofs/examples/shuffle_api.rs
halo2_proofs/src/dev.rs
halo2_proofs/src/dev/failure.rs
halo2_proofs/src/plonk.rs
halo2_proofs/src/plonk/circuit.rs
halo2_proofs/src/plonk/evaluation.rs
halo2_proofs/src/plonk/prover.rs
halo2_proofs/src/plonk/shuffle.rs
halo2_proofs/src/plonk/shuffle/prover.rs
halo2_proofs/src/plonk/shuffle/verifier.rs
halo2_proofs/src/plonk/verifier.rs

Some dynamic lookup applications require only one-to-one mapping between expressions. Currently such applications are applied using subset argument and `ConstraintSystem::lookup` API. However It would be more efficient to use shuffle argument which looks like below:
$$
Z(ωX)⋅(S(X)+γ)−Z(X)⋅(A(X)+γ) = 0
$$
So that we can save two permutation witness columns introduced in subset argument. Even this argument can be applied using challenge API, for complex circuits it would be very hard to track cell values that are required for grand product. Implementation method in this PR is just straightforward. Many subset argument related thigs are jsut copied and named as *shuffle* and required fixes are applied. In the end with this PR we will have `ConstraintSystem::shuffle` API.

Implement native shuffle argument and api

---

halo2_gadgets/Cargo.toml
halo2_proofs/Cargo.toml

Halo2curve's package release resets the version from those inherited by the legacy halo2curves repo's fork history.
This sets the halo2curve dependency to use the released crate.
The upstream diff is:
https://github.com/privacy-scaling-explorations/halo2curves/compare/9f5c50810bbefe779ee5cf1d852b2fe85dc35d5e..9a7f726fa74c8765bc7cdab11519cf285d169ecf
This addresses https://github.com/privacy-scaling-explorations/halo2curves/issues/63 and allows halo2curves to develop tagging. Should you not want to take the upgrade, another option is to depend on halo2curves at a particular git commit hash (rather than a tag), ideally the one pointed at by v0.3.2, i.e. https://github.com/privacy-scaling-explorations/halo2curves/commit/9f5c50810bbefe779ee5cf1d852b2fe85dc35d5e. I'm happy to amend the current …

Updates halo2_curves dependency to released package

---

halo2_gadgets/src/poseidon/primitives/mds.rs

Certain compiler versions, and targets, particularly `wasm-unknown-unknown`, error out on the following lines of `halo2_gadgets/src/poseidon/primitives/mds.rs:85:28`: 
```rust
} else {
// We can invert freely; by construction, the elements of xs are distinct.
acc * (x - x_m) * (x_j - x_m).invert().unwrap()
}
})
};
```
with the error 
```bash
let diff = (x_j - *x_m).invert();
|       ^^^^^^^^^^^^ cannot infer type
```
This PR applies a simple patch to allow for compilation for those targets !

fix: explicitly define mds diff type

---

.github/workflows/docs-ghpages.yml

Created a github action workflow to host the docs on to github pages. Added an `index.html` at the root of `docs` folder.

Host docs ghpages

---

.github/workflows/docs-ghpages.yml

Currently, if we go `https://privacy-scaling-explorations.github.io/halo2/`, it gets redirected to `https://privacy-scaling-explorations.github.io/halo2/pse_halo2`, which is not a valid URL.
We fixed the index page to redirect to a valid crate page. I think halo2_proofs is the most helpful destination for readers.

Fix gh page doc index

---

halo2_proofs/src/poly/kzg/commitment.rs

Hi guys, I'm learning KZG so I checked `halo2` source code. Found some minor issues and can be improved.
```rust
let mut root = <Bn256 as Engine>::Scalar::ROOT_OF_UNITY_INV
.invert()
.unwrap();
for _ in k..<Bn256 as Engine>::Scalar::S {
root = root.square();
}
```
Is equivalent to 
```rust
let root = <Bn256 as Engine>::Scalar::ROOT_OF_UNITY
.pow_vartime([1 << (<Bn256 as Engine>::Scalar::S - k)]);
```
Result:
```text
root-of-unity time:   [1.4413 µs 1.4443 µs 1.4473 µs]                           
change: [-89.921% -89.897% -89.873%] (p = 0.00 < 0.05)
Performance has improved.
```

Improve root calculation for KZG setup()

---

halo2_proofs/src/plonk/circuit.rs

Fixes #205
If there was a reason not to make Expression Eq let me know. I did it for tests. I can remove it.

Implement Sum and Product for Expression

---

halo2_proofs/src/arithmetic.rs

The multi-scalar multiplication algorithms in halo2 are written for scalars of 32 bytes. This PR uses generics (`NUM_BITS`) to make the algorithm generic over larger Scalar fields (such as those of [Pluto/Eris curves](https://github.com/daira/pluto-eris)).

Make multi scalar multiplication generic on the size of the Scalar

---

halo2_gadgets/src/utilities/lookup_range_check.rs
halo2_proofs/src/poly/commitment.rs
halo2_proofs/src/transcript.rs

chore: fix typos in comments

---

halo2_proofs/src/helpers.rs
halo2_proofs/src/plonk.rs
halo2_proofs/src/plonk/circuit.rs
halo2_proofs/src/plonk/keygen.rs
halo2_proofs/src/plonk/permutation.rs

Selector compression is an optimization, but often it can lead to unexpected behavior / makes life complicated when doing more complicated proof composability like with SNARK recursion or universal verifiers such as in `snark-verifier` and `halo2-solidity-verifier`. As such, it is useful to be able to optionally turn it off.
This PR does the following:
- Addresses https://github.com/privacy-scaling-explorations/halo2/issues/176 by adding a version byte to vkey serialization and using little endian everywhere for consistency.
- Adds `keygen_vk_custom` function where user can choose whether to turn on selector compression(=combination) or not.
- For backwards compatibility, `keygen_vk` will be set so the default is with selector compression, so it matches current behavior.
- When selector …

[feat] Make selector compression optional

---

halo2_proofs/src/poly/kzg/multiopen/shplonk/prover.rs

Fix typos in SHPlonk prover code

chore: fix typos

---

README.md
book/src/SUMMARY.md
book/src/user/experimental-features.md
halo2_proofs/src/plonk/circuit.rs

Resolves #223 
Also pick the fix from #195

Document PSE fork features

---

halo2_proofs/src/poly/query.rs

This pull request was created to solve the issue that mentioned in  #230

Publish necessary properties for external use of KZG commitment

---

halo2_proofs/src/poly/domain.rs

Recently in zkEVM proof chunk we introduce `user-challenge` to derive application level challenge by random oracle with selected columns commitments. To derive commitment of advices column, we follow halo2 create_proof api, where one of the halo2 domain api need to adjust visibility to public, since this is the only way to derive `Polynomial<Assigned<F>, LagrangeCoeff>` type.
Furthermore, another domain api `fn empty_lagrange` is also public so it make sense for `fn empty_lagrange_assigned` as well.
reference usecase zkEVM PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1709

chores: adjust domain api visibility

---

halo2_proofs/Cargo.toml

Sometimes we want to be able to serialize Fr. However feature `derive_serde` is available on `halo2curves`. This PR adds a feature `derive_serde` to halo2_proofs which activates `derive_serde` feature on `halo2curves`.

Add derive_serde feature

---

halo2_proofs/src/dev.rs

This information is useful for debugging tools that inspect advice cells and more data.

Expose mockprover data

---

halo2_backend/src/helpers.rs
halo2_backend/src/plonk.rs
halo2_backend/src/plonk/lookup.rs
halo2_backend/src/plonk/permutation.rs
halo2_backend/src/plonk/permutation/prover.rs
halo2_backend/src/plonk/permutation/verifier.rs
halo2_backend/src/plonk/shuffle.rs
halo2_backend/src/plonk/shuffle/verifier.rs
halo2_backend/src/poly.rs
halo2_backend/src/poly/ipa/commitment.rs
halo2_backend/src/poly/ipa/msm.rs
halo2_backend/src/poly/ipa/multiopen.rs
halo2_backend/src/poly/ipa/multiopen/prover.rs
halo2_backend/src/poly/ipa/strategy.rs
halo2_backend/src/poly/kzg/commitment.rs
halo2_backend/src/poly/kzg/msm.rs
halo2_backend/src/poly/kzg/strategy.rs
halo2_backend/src/poly/query.rs
halo2_common/src/circuit/floor_planner/v1/strategy.rs
halo2_common/src/circuit/table_layouter.rs
halo2_common/src/plonk/circuit.rs
halo2_common/src/plonk/lookup.rs
halo2_common/src/plonk/permutation.rs
halo2_frontend/src/dev/cost.rs
halo2_frontend/src/dev/metadata.rs
halo2_frontend/src/dev/util.rs

- review & correct the pub types/fields in every crate
- #259  
- correct the pub types/fields in following crates:
`halo2_common`, `halo2_frontend`, `halo2_backend`

fix: correct the pub types/fields(post frontend-backend split)

---

Cargo.toml
halo2_backend/Cargo.toml
halo2_common/Cargo.toml
halo2_frontend/Cargo.toml
halo2_middleware/Cargo.toml
halo2_proofs/Cargo.toml

- roll back the `getrandom` crate import change caused by #281 
- Close #285 
- set the `getrandom` crate as `dev-dependency` for `wasm32-*` target build CI
- remove the `resolver = "2"` option from workspace cargo.toml

fix: reset the changes introduced in `getrandom` import as dep

---

halo2_frontend/src/dev/failure.rs

This way, users can pretty-print the error while still catching the verification failure. As far as I can see, printing the error is otherwise only exposed via `MockProver::assert_satisfied`.

Make `VerifyFailure::emit` public

---

halo2_backend/src/plonk/evaluation.rs
halo2_backend/src/plonk/keygen.rs
halo2_backend/src/plonk/lookup/verifier.rs
halo2_backend/src/plonk/shuffle/verifier.rs
halo2_backend/src/plonk/verifier.rs
halo2_frontend/src/plonk/circuit/expression.rs
halo2_middleware/src/expression.rs

This simplifies the code a bit.  I've only applied this change in the middleware and backend.  The frontend `Expression` stays intact in order to not break the frontend public API.
The proposal behind this change is to simplify the handling of Expression at a negligible cost.  The only benefit I saw from the `Expression::Scaled` case was avoiding a heap allocation; but I don't think heap allocations from expressions have any impact on the memory usage and performance because:
- In a circuit the number of expressions is small, compared to other things like witness size
- When calculating a proof, the expression is not traversed many times
I can only imagine this could affect the performance if the expression is traversed many times (although probably the performance impact is really …

chore: remove generic Expression::Scaled in favor of Product

---

halo2_backend/src/plonk/keygen.rs
halo2_backend/src/plonk/prover.rs
halo2_frontend/src/circuit.rs
halo2_middleware/src/circuit.rs
halo2_proofs/src/plonk/keygen.rs
halo2_proofs/src/plonk/prover.rs
halo2_proofs/tests/frontend_backend_split.rs

There were a few type names that included "V2" after the frontend-backend split but they don't collide between frontend-middleware-backend so the "V2" was unneeded.  With this PR the names after the frontend-backend split will be uniform.
Resolve https://github.com/privacy-scaling-explorations/halo2/issues/263

chore: remove V2 from type names

---

halo2_backend/Cargo.toml
halo2_frontend/Cargo.toml
halo2_proofs/Cargo.toml

Check & enable the `halo2_backend` & `halo2_frontend` features in `halo2_proofs` crate features
- None
- remove `gadget-traces` & `cost-estimator` feature from `halo2_backend` crate features
- remove `sanity-checks` feature from `halo2_frontend` crate features
- enable the necessary features in `halo2_proofs` crate features

fix: enable the features in `halo2_proofs` crate

---

halo2_backend/src/plonk/keygen.rs
halo2_backend/src/plonk/lookup/prover.rs
halo2_backend/src/plonk/permutation/keygen.rs
halo2_backend/src/plonk/permutation/prover.rs
halo2_backend/src/plonk/verifier.rs
halo2_backend/src/poly/ipa/commitment.rs
halo2_backend/src/poly/ipa/commitment/prover.rs

Analyze and apply the `tachyon` optimizations - **2(batch normalize)** & **5(save heap allocations)**
- #293 
- apply the `batch_normalize` in everywhere possible of `halo2_backend` crate 
1. `batch_normalize`
In order to apply the `batch_normalize` optimization, the algorithm of `batch_normalize` & `batch_inverse` should be implemented for elliptic curves. It is already implemented in [pse/halo2curves](https://github.com/privacy-scaling-explorations/halo2curves/blob/main/src/derive/curve.rs#L775-L806) repo.
2. `save heap allocations`
For this optimization, I just apply one - remove unnecessary "clone" op in ["permutation_commit"](halo2_backend/src/plonk/permutation/prover.rs).
The reason is that other optimizations needless in Rust project. 
Also, the `Polynomial` implementation has big …

improve: apply `tachyon` optimizations(2 & 5)

---

halo2_backend/Cargo.toml
halo2_frontend/Cargo.toml
halo2_middleware/Cargo.toml
halo2_proofs/Cargo.toml

Upgrade the `halo2cuves` dep to `0.6.1`
- Resolve #326

minor: upgrade the `halo2curves` dep to 0.6.1

---

.github/workflows/docs-ghpages.yml

In https://github.com/privacy-scaling-explorations/halo2/pull/306 we bumped the rust version to 1.78 and that broke the docs build which was using a nightly version from 2023.
Bumping the nightly version used to build the docs should fix the issue.

fix: bump nightly version to build docs in CI

---

halo2_backend/src/plonk/circuit.rs
halo2_proofs/tests/plonk_api.rs

- Add more conditionally-debugged fields to `transcript_repr`
- Resolve #350 
- add multi-phase related challenge fields to `PinnedConstraintSystem::fmt`
- update the `plonk_api` test

patch: include more fields to transcript

---

.github/scripts/wasm-target-test-build.sh
.github/workflows/ci.yml
halo2_frontend/Cargo.toml
halo2_frontend/src/dev.rs
halo2_frontend/src/plonk/circuit/constraint_system.rs
halo2_frontend/src/plonk/circuit/expression.rs
halo2_proofs/Cargo.toml
halo2_proofs/tests/frontend_backend_split.rs

Dynamic lookup, which uses the `lookup_any`, should have the assertion to prevent use of `Advice/Instance` column without extra `Fixed` column or `Selector`.
This PR adds assertion to `lookup_any` api.
- Resolve #224 #335 
- add assertion of `table_expression` containing `fixed` col or `selector` in `lookup_any` api
- add extra check that `table_expression` should NOT be one simple `fixed` col, in `lookup_any` api
- update/add the unit tests

feat: add assertion for dynamic lookup

---

halo2_frontend/src/dev.rs
halo2_proofs/Cargo.toml

`halo2_proofs` was importing `halo2_frontend` with the default features, so there was no way to disable `lookup-any-sanity-checks` when using `halo2_proofs`.
Now `halo2_proofs` imports `halo2_frontend` without default features, and the dependencies features are completely controlled by the user via the `halo2_proofs` features.  I did the same for `halo2_backend` to achieve the same level of control.

fix: make lookup-any-sanity-checks optional in halo2_proofs

---

halo2_proofs/benches/plonk.rs

Correct the `plonk` benchmarking code - `prover` and `verifier` bench
- None
- set the number of instances in bench as 0

fix: correct the "plonk" benchmarking

---

halo2_frontend/src/circuit.rs
halo2_frontend/src/dev.rs
halo2_frontend/src/plonk/error.rs
halo2_frontend/src/plonk/keygen.rs

- Improve the error handling related to `Error::Synthesis`
- Resolve  #219 
- Add `WitnessMissing` variant to `AssignError`

feat: improve error handling(Error::Synthesis)

---

halo2_backend/src/plonk/prover.rs
halo2_backend/src/plonk/verifier.rs
halo2_backend/src/plonk/verifier/batch.rs
halo2_backend/src/poly/ipa/strategy.rs
halo2_backend/src/poly/kzg/strategy.rs
halo2_backend/src/poly/multiopen_test.rs
halo2_backend/src/poly/strategy.rs
halo2_proofs/benches/plonk.rs
halo2_proofs/src/plonk.rs
halo2_proofs/src/plonk/prover.rs
halo2_proofs/tests/compress_selectors.rs
halo2_proofs/tests/frontend_backend_split.rs
halo2_proofs/tests/plonk_api.rs
halo2_proofs/tests/serialization.rs
halo2_proofs/tests/shuffle.rs
halo2_proofs/tests/shuffle_api.rs
halo2_proofs/tests/vector-ops-unblinded.rs
p3_frontend/tests/common/mod.rs

Improve the verify api - `verify_proof`, in a way that it does return the `bool` value indicating proof is valid or not.
This way, we remove the confusion or misuse, related to `verify_proof` api.
- Resolve #184 
- Update several `VerificationStrategy` impls 
- Update the `verify_proof` so that it returns the `bool` 
- Update the related tests

feat: refactor the verify api

---

halo2_backend/src/plonk/prover.rs
halo2_backend/src/plonk/vanishing.rs
halo2_proofs/src/plonk/prover.rs

- Split the `create_proof` function into focused/stage functions
- Resolve #247 
- create new focused/stage functions in `Prover` struct, like `gen_permuted_lookups`, ...
- refactor the `create_proof` so that it uses the stage functions

feat: split `create_proof` 

---

halo2_backend/src/plonk/evaluation.rs

If input expression of a shuffle contains more rotations than shuffle expression, the code will abort.
I believe this is a typo.

fix(evaluation): fix the wrong eval_data of input_evaluator in shuffle

---

halo2_backend/src/arithmetic.rs
halo2_backend/src/plonk/circuit.rs
halo2_backend/src/plonk/evaluation.rs
halo2_backend/src/plonk/keygen.rs
halo2_backend/src/plonk/lookup/verifier.rs
halo2_backend/src/plonk/permutation.rs
halo2_backend/src/plonk/permutation/keygen.rs
halo2_backend/src/plonk/permutation/prover.rs
halo2_backend/src/plonk/permutation/verifier.rs
halo2_backend/src/plonk/shuffle/verifier.rs
halo2_backend/src/plonk/vanishing/prover.rs
halo2_backend/src/plonk/verifier.rs
halo2_backend/src/poly/domain.rs
halo2_proofs/tests/compress_selectors.rs
halo2_proofs/tests/frontend_backend_split.rs
halo2_proofs/tests/plonk_api.rs
halo2_proofs/tests/serialization.rs
halo2_proofs/tests/shuffle.rs
halo2_proofs/tests/shuffle_api.rs
halo2_proofs/tests/vector-ops-unblinded.rs

- Take care of some TODOs throughout the repo
-
- ~~parallelize `compute_inner_product` utility~~
- use `ColumnMid` in `QueryBack`
- remove renaming in `halo2_backend/plonk/permutation`
- refactor the `EvaluationDomain::extended_to_coeff` function

chore: remove some TODOs from codebase

---

.github/scripts/run-examples.sh

- Add quotes around variables in cargo run commands
- Add quotes around command substitutions
- Prevent potential issues with filenames containing spaces or special characters

fix: Add quotes around variables in run-examples.sh
